### ISSUE TITLE
imrprovement/queueMonograph

### ISSUE THREAD

**Issue by gregoryyoung2** [gregoryyoung2/CSE231Winter2016-GroupProject-Team5#9]
Search method just searches the underlying array not the queue. Check out improvement/queue and see how they search, we should implement something like that for this class.

**Comment by jeremyxy** [comment]
Fixed issues. About to upload final product.

**Comment by gregoryyoung2** [comment]
@jeremyxy Hey, it looks like you forgot to commit the changes requested in this issue before you merged the pull request. The search method still searches the underlying array instead of using the queue methods. Could you commit this to the branch and make another pull request? Thanks!

**Comment by jeremyxy** [comment]
Sorry. I didn't want to make another pull request till I tested the new code. I'll make that new commit and pull request now

**Comment by jeremyxy** [comment]
@gregoryyoung2 Code is tested and pull request with new code has been made. I'll close it tonight if no issues are found.
